FROM python:3.9-alpine

WORKDIR /yepcord

RUN python -m pip install --upgrade pip && pip install --upgrade wheel setuptools
RUN pip install websockets

COPY ./internal/pubsub/main.py .

CMD ["python", "main.py"]