FROM python:3.9-alpine

RUN apk update && apk add gcc libc-dev libmagic
RUN python -m pip install --upgrade pip && pip install --upgrade wheel setuptools
COPY requirements.txt requirements.txt
COPY requirements-s3.txt requirements-s3.txt

RUN pip install -r requirements.txt
RUN pip install -r requirements-s3.txt

COPY . .

CMD ["/bin/ash"]