"""add all models

Revision ID: 5af66bf76735
Revises: eb03915355af
Create Date: 2023-06-21 20:07:39.502968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af66bf76735'
down_revision = 'eb03915355af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('features', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('splash', sa.String(length=256), nullable=True),
    sa.Column('discovery_splash', sa.String(length=256), nullable=True),
    sa.Column('banner', sa.String(length=256), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('afk_channel', sa.BigInteger(), nullable=True),
    sa.Column('system_channel', sa.BigInteger(), nullable=True),
    sa.Column('afk_timeout', sa.Integer(), nullable=True),
    sa.Column('verification_level', sa.Integer(), nullable=True),
    sa.Column('default_message_notifications', sa.Integer(), nullable=True),
    sa.Column('mfa_level', sa.Integer(), nullable=True),
    sa.Column('explicit_content_filter', sa.Integer(), nullable=True),
    sa.Column('system_channel_flags', sa.BigInteger(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('vanity_url_code', sa.String(length=64), nullable=True),
    sa.Column('preferred_locale', sa.String(length=8), nullable=True),
    sa.Column('premium_progress_bar_enabled', sa.Boolean(), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('nsfw_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_guilds_users_id_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mfacodes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_mfacodes_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditlogentrys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('changes', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('options', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_auditlogentrys_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_auditlogentrys_users_id_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('user_limit', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('owner', sa.BigInteger(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('rtc_region', sa.String(length=64), nullable=True),
    sa.Column('video_quality_mode', sa.Integer(), nullable=True),
    sa.Column('default_auto_archive', sa.Integer(), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_channels_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_channels_users_id_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent'], ['channels.id'], name='fk_channels_channels_id_parent', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emojis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('require_colons', sa.Boolean(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=True),
    sa.Column('animated', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_emojis_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_emojis_users_id_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildbans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_guildbans_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_guildbans_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildmembers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('communication_disabled_until', sa.BigInteger(), nullable=True),
    sa.Column('flags', sa.BigInteger(), nullable=True),
    sa.Column('nick', sa.String(length=128), nullable=True),
    sa.Column('mute', sa.Boolean(), nullable=True),
    sa.Column('deaf', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_guildmembers_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_guildmembers_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildtemplates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('usage_count', sa.BigInteger(), nullable=True),
    sa.Column('creator', sa.BigInteger(), nullable=True),
    sa.Column('serialized_guild', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_dirty', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], name='fk_guildtemplates_users_id_creator', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_guildtemplates_guilds_id_guild', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('color', sa.BigInteger(), nullable=True),
    sa.Column('hoist', sa.Boolean(), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=True),
    sa.Column('mentionable', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('unicode_emoji', sa.String(length=256), nullable=True),
    sa.Column('flags', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_roles_guilds_id_guild', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stickers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_stickers_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_stickers_users_id_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_channels_users_channels_channel_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_channels_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildevents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('creator', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('privacy_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_metadata', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_guildevents_channels_id_channel', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], name='fk_guildevents_users_id_creator', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_guildevents_guilds_id_guild', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildmembers_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=True),
    sa.Column('guildmember', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guildmember'], ['guildmembers.id'], name='fk_guildmembers_roles_guildmembers_guildmember_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_guildmembers_roles_roles_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiddendmchannels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_hiddendmchannels_channels_id_channel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_hiddendmchannels_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'channel', name='uc_hiddendmchannels_user_channel')
    )
    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('inviter', sa.BigInteger(), nullable=True),
    sa.Column('max_age', sa.BigInteger(), nullable=False),
    sa.Column('max_uses', sa.BigInteger(), nullable=True),
    sa.Column('uses', sa.BigInteger(), nullable=True),
    sa.Column('vanity_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_invites_channels_id_channel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter'], ['users.id'], name='fk_invites_users_id_inviter', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('author', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('embeds', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('webhook_id', sa.BigInteger(), nullable=True),
    sa.Column('webhook_author', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('application', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=True),
    sa.Column('message_reference', sa.JSON(), nullable=False),
    sa.Column('thread', sa.BigInteger(), nullable=True),
    sa.Column('components', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('sticker_items', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('stickers', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('extra_data', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name='fk_messages_users_id_author', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_messages_channels_id_channel', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_messages_guilds_id_guild', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread'], ['channels.id'], name='fk_messages_channels_id_thread', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissionoverwrites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('allow', sa.BigInteger(), nullable=False),
    sa.Column('deny', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_permissionoverwrites_channels_id_channel', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readstates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('last_read_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_readstates_channels_id_channel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_readstates_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threadmembers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_threadmembers_channels_id_channel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_threadmembers_guilds_id_guild', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_threadmembers_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threadmetadatas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('archive_timestamp', sa.DateTime(), nullable=False),
    sa.Column('auto_archive_duration', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_threadmetadatas_channels_id_channel', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_webhooks_channels_id_channel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_webhooks_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], name='fk_attachments_channels_id_channel', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message'], ['messages.id'], name='fk_attachments_messages_id_message', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guildevents_guildmembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guildmember', sa.BigInteger(), nullable=True),
    sa.Column('guildevent', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guildevent'], ['guildevents.id'], name='fk_guildevents_guildmembers_guildevents_guildevent_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guildmember'], ['guildmembers.id'], name='fk_guildevents_guildmembers_guildmembers_guildmember_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactionss',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('emoji', sa.BigInteger(), nullable=True),
    sa.Column('emoji_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['emoji'], ['emojis.id'], name='fk_reactionss_emojis_id_emoji', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message'], ['messages.id'], name='fk_reactionss_messages_id_message', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_reactionss_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactionss')
    op.drop_table('guildevents_guildmembers')
    op.drop_table('attachments')
    op.drop_table('webhooks')
    op.drop_table('threadmetadatas')
    op.drop_table('threadmembers')
    op.drop_table('readstates')
    op.drop_table('permissionoverwrites')
    op.drop_table('messages')
    op.drop_table('invites')
    op.drop_table('hiddendmchannels')
    op.drop_table('guildmembers_roles')
    op.drop_table('guildevents')
    op.drop_table('channels_users')
    op.drop_table('stickers')
    op.drop_table('roles')
    op.drop_table('guildtemplates')
    op.drop_table('guildmembers')
    op.drop_table('guildbans')
    op.drop_table('emojis')
    op.drop_table('channels')
    op.drop_table('auditlogentrys')
    op.drop_table('mfacodes')
    op.drop_table('guilds')
    # ### end Alembic commands ###
