"""set bio field as not null

Revision ID: a58a63d40123
Revises: 3b83b488d232
Create Date: 2023-07-13 17:22:00.934079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58a63d40123'
down_revision = '3b83b488d232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
