"""create user tables

Revision ID: eb03915355af
Revises: 
Create Date: 2023-06-20 19:02:33.310854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb03915355af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('frecencysettingss',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_frecencysettingss_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user1', sa.BigInteger(), nullable=True),
    sa.Column('user2', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user1'], ['users.id'], name='fk_relationships_users_id_user1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2'], ['users.id'], name='fk_relationships_users_id_user2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_sessions_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdatas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('discriminator', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('flags', sa.BigInteger(), nullable=False),
    sa.Column('public_flags', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.String(length=256), nullable=True),
    sa.Column('accent_color', sa.BigInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('avatar_decoration', sa.String(length=256), nullable=True),
    sa.Column('banner', sa.String(length=256), nullable=True),
    sa.Column('banner_color', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_userdatas_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'discriminator', name='uc_userdatas_username_discriminator')
    )
    op.create_table('usernotes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['target'], ['users.id'], name='fk_usernotes_users_id_target', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_usernotes_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersettingss',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('inline_attachment_media', sa.Boolean(), nullable=True),
    sa.Column('show_current_game', sa.Boolean(), nullable=True),
    sa.Column('view_nsfw_guilds', sa.Boolean(), nullable=True),
    sa.Column('enable_tts_command', sa.Boolean(), nullable=True),
    sa.Column('render_reactions', sa.Boolean(), nullable=True),
    sa.Column('gif_auto_play', sa.Boolean(), nullable=True),
    sa.Column('stream_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('animate_emoji', sa.Boolean(), nullable=True),
    sa.Column('view_nsfw_commands', sa.Boolean(), nullable=True),
    sa.Column('detect_platform_accounts', sa.Boolean(), nullable=True),
    sa.Column('default_guilds_restricted', sa.Boolean(), nullable=True),
    sa.Column('allow_accessibility_detection', sa.Boolean(), nullable=True),
    sa.Column('native_phone_integration_enabled', sa.Boolean(), nullable=True),
    sa.Column('contact_sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('disable_games_tab', sa.Boolean(), nullable=True),
    sa.Column('developer_mode', sa.Boolean(), nullable=True),
    sa.Column('render_embeds', sa.Boolean(), nullable=True),
    sa.Column('message_display_compact', sa.Boolean(), nullable=True),
    sa.Column('convert_emoticons', sa.Boolean(), nullable=True),
    sa.Column('passwordless', sa.Boolean(), nullable=True),
    sa.Column('personalization', sa.Boolean(), nullable=True),
    sa.Column('usage_statistics', sa.Boolean(), nullable=True),
    sa.Column('inline_embed_media', sa.Boolean(), nullable=True),
    sa.Column('use_thread_sidebar', sa.Boolean(), nullable=True),
    sa.Column('use_rich_chat_input', sa.Boolean(), nullable=True),
    sa.Column('expression_suggestions_enabled', sa.Boolean(), nullable=True),
    sa.Column('view_image_descriptions', sa.Boolean(), nullable=True),
    sa.Column('afk_timeout', sa.Integer(), nullable=True),
    sa.Column('explicit_content_filter', sa.Integer(), nullable=True),
    sa.Column('timezone_offset', sa.Integer(), nullable=True),
    sa.Column('friend_discovery_flags', sa.Integer(), nullable=True),
    sa.Column('animate_stickers', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=8), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('mfa', sa.String(length=64), nullable=True),
    sa.Column('render_spoilers', sa.String(length=16), nullable=True),
    sa.Column('dismissed_contents', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('custom_status', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('activity_restricted_guild_ids', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('friend_source_flags', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('guild_positions', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('guild_folders', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('restricted_guilds', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_usersettingss_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersettingss')
    op.drop_table('usernotes')
    op.drop_table('userdatas')
    op.drop_table('sessions')
    op.drop_table('relationships')
    op.drop_table('frecencysettingss')
    op.drop_table('users')
    # ### end Alembic commands ###
